#ifndef LIBPACSYNC_GLOBAL_H
#define LIBPACSYNC_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PACSYNC_LIBRARY)
#  define LIBPACSYNC_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBPACSYNC_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBPACSYNC_GLOBAL_H
